#!/usr/bin/env python3

from bs4 import BeautifulSoup
import requests
import re
import json
import sys


url = str(sys.argv[1])
response = requests.get(url)
soup = BeautifulSoup(response.text, 'lxml')

movies = soup.select('td.titleColumn')
links = [a.attrs.get('href') for a in soup.select('td.titleColumn a')]
crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
sum = [a.attrs.get('summary_text') for a in soup.select('td.titleColumn a')]
ratings = [b.attrs.get('data-value') for b in soup.select('td.posterColumn span[name=ir]')]
votes = [b.attrs.get('data-value') for b in soup.select('td.ratingColumn strong')]

imdb = []

index = int(sys.argv[2]) - 1

movie_string = movies[index].get_text()
movie = (' '.join(movie_string.split()).replace('.', ''))
movie_title = movie[len(str(index))+1:-7]
year = re.search('\((.*?)\)', movie_string).group(1)
place = movie[:len(str(index))-(len(movie))]

sub = 'https://www.imdb.com/' + links[index]

req = requests.get(sub)
soup1 = BeautifulSoup(req.text, 'html.parser')
summary = soup1.find("div", class_="summary_text").contents[0].strip()
sub_text = soup1.find("div", class_="subtext")

duration = sub_text.find("time").contents[0].strip()
genre = []
for a in sub_text.find_all("a"):
    if "genre" in a["href"]:
        genre.append(a.contents[0])

data = [{"title": movie_title,
        "movie_release_year": year,
        "imdb_rating": round(float(ratings[index].strip(' "')), 1),
        "summary": summary,
        "duration": duration,
        "genre": ','.join(genre)}]


print(json.dumps(data))
